# Generated by Django 3.2 on 2022-09-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(choices=[('gold', 'GOLD'), ('silver', 'SILVER'), ('bronze', 'BRONZE')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('service technician', 'SERVICE TECHNICIAN'), ('diagnostic technician', 'DIAGNOSTIC TECHNICIAN'), ('vehicle refinisher', 'VEHICLE REFINISHER'), ('body repair technician', 'BODY REPAIR TECHNICIAN'), ('vehicle inspector', 'VEHICLE INSPECTOR'), ('brake and transmission technician', 'BRAKE AND TRANSMISSION TECHNICIAN')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=30)),
                ('lng', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(default='default_technician_photo', upload_to='photos/technician/')),
                ('shop_description', models.TextField()),
                ('shop_goal', models.TextField()),
                ('rating', models.FloatField(default=0)),
                ('autouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_badge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.skillbadge')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ManyToManyField(blank=True, to='technician.Specialization')),
                ('technician', models.ManyToManyField(blank=True, to='technician.TechnicianDetails')),
            ],
        ),
        migrations.CreateModel(
            name='ShopFeedbackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('autouser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='technician.techniciandetails')),
            ],
        ),
    ]
