# Generated by Django 3.2 on 2022-11-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianspecializations',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='specializations', to='technician.Specialization'),
        ),
        migrations.AlterField(
            model_name='technicianspecializations',
            name='technician',
            field=models.ManyToManyField(blank=True, related_name='technicianspecialization', to='technician.TechnicianDetails'),
        ),
    ]
