# Generated by Django 3.2 on 2022-11-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_auto_20221110_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfeedbackrating',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicianfeedback', to='technician.techniciandetails'),
        ),
        migrations.AlterField(
            model_name='technicianspecializations',
            name='technician',
            field=models.ManyToManyField(blank=True, related_name='technician_specialization', to='technician.TechnicianDetails'),
        ),
    ]
