# Generated by Django 3.2 on 2022-11-10 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0003_auto_20221110_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfeedbackrating',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_feedback', to='technician.techniciandetails'),
        ),
    ]
