# Generated by Django 3.2 on 2022-11-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0004_alter_shopfeedbackrating_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciandetails',
            name='region',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
    ]
