# Generated by Django 3.2 on 2022-11-15 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('technician', '0005_technician_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('autouser_description', models.TextField()),
                ('technician_description', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('auto_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autouser_booking', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_booking', to='technician.techniciandetails')),
            ],
        ),
    ]
